export const PILOT_USERS = [
    {
        id: "USR-001",
        name: "Abraham Tefera",
        email: "abraham.admin@aires.et",
        phone: "+251911000001",
        role: "ADMIN",
        active: true,
    },
    {
        id: "USR-002",
        name: "Endalkachew Bekele",
        email: "endalk.manager@aires.et",
        phone: "+251911000002",
        role: "MANAGER",
        active: true,
    },
    {
        id: "USR-003",
        name: "Dawit Haile (Agent 1)",
        email: "agent1@aires.et",
        phone: "+251911223344",
        role: "FIELD_AUDITOR",
        active: true,
    },
    {
        id: "USR-004",
        name: "Marta Girma (Agent 2)",
        email: "agent2@aires.et",
        phone: "+251911223345",
        role: "FIELD_AUDITOR",
        active: true,
    },
    {
        id: "USR-005",
        name: "Yared Tadesse (Agent 3)",
        email: "agent3@aires.et",
        phone: "+251911223346",
        role: "FIELD_AUDITOR",
        active: true,
    },
    {
        id: "USR-006",
        name: "Selam Fikru (Agent 4)",
        email: "agent4@aires.et",
        phone: "+251911223347",
        role: "FIELD_AUDITOR",
        active: true,
    },
];

export const PILOT_COMPETITORS = [
    { id: "allmart", name: "Allmart", type: "FMCG", active: true },
    { id: "abadir", name: "Abadir", type: "FMCG", active: true },
    { id: "shoa", name: "Shoa", type: "FMCG", active: true },
    { id: "bambis", name: "Bambis", type: "FMCG", active: true },
    { id: "fresh-corner", name: "Fresh Corner", type: "FRESH", active: true },
    { id: "garment-market", name: "Garment Vegetable Market", type: "FRESH", active: true },
    { id: "straight-market", name: "Straight Market", type: "FRESH", active: true },
];

export const PILOT_STORES = [
    {
        id: "STR-ALLMART-BOLE",
        competitorId: "allmart",
        name: "Allmart Supermarket - Bole",
        address: "Bole Medhanialem Road, Addis Ababa",
        city: "Addis Ababa",
        area: "Bole",
        type: "FMCG",
        latitude: 8.9984120,
        longitude: 38.7865200,
        active: true,
    },
    {
        id: "STR-ABADIR-PIASSA",
        competitorId: "abadir",
        name: "Abadir Supermarket - Piassa",
        address: "Piassa Churchill Ave, Addis Ababa",
        city: "Addis Ababa",
        area: "Piassa",
        type: "FMCG",
        latitude: 9.0304500,
        longitude: 38.7521000,
        active: true,
    },
    {
        id: "STR-SHOA-BOLE",
        competitorId: "shoa",
        name: "Shoa Supermarket - Bole Road",
        address: "Africa Avenue, Bole, Addis Ababa",
        city: "Addis Ababa",
        area: "Bole",
        type: "FMCG",
        latitude: 9.0012400,
        longitude: 38.7712300,
        active: true,
    },
    {
        id: "STR-BAMBIS-KAZANCHIS",
        competitorId: "bambis",
        name: "Bambis Supermarket - Kazanchis",
        address: "Jomo Kenyatta St, Kazanchis, Addis Ababa",
        city: "Addis Ababa",
        area: "Kazanchis",
        type: "FMCG",
        latitude: 9.0156700,
        longitude: 38.7698000,
        active: true,
    },
    {
        id: "STR-FRESH-CORNER-OLD-AIRPORT",
        competitorId: "fresh-corner",
        name: "Fresh Corner - Old Airport",
        address: "South Africa St, Old Airport, Addis Ababa",
        city: "Addis Ababa",
        area: "Old Airport",
        type: "FRESH",
        latitude: 8.9892000,
        longitude: 38.7345000,
        active: true,
    },
    {
        id: "STR-GARMENT-MARKET",
        competitorId: "garment-market",
        name: "Garment Vegetable Market - Jomo",
        address: "Garment Roundabout, Jomo Road, Addis Ababa",
        city: "Addis Ababa",
        area: "Garment / Jomo",
        type: "FRESH",
        latitude: 8.9654000,
        longitude: 38.7241000,
        active: true,
    },
    {
        id: "STR-STRAIGHT-MARKET-SARIS",
        competitorId: "straight-market",
        name: "Straight Market - Saris",
        address: "Debre Zeit Road, Saris, Addis Ababa",
        city: "Addis Ababa",
        area: "Saris",
        type: "FRESH",
        latitude: 8.9482000,
        longitude: 38.7615000,
        active: true,
    },
];

export const PILOT_PRODUCTS_20 = [
    // Fresh Produce (5 Items)
    { id: "VEG-01", name: "Red Onion", category: "Fresh", unit: "kg", sku: "SKU-VEG-01", barcode: "6001001", queensPrice: 64.00, active: true },
    { id: "VEG-02", name: "Potato", category: "Fresh", unit: "kg", sku: "SKU-VEG-02", barcode: "6001002", queensPrice: 48.00, active: true },
    { id: "VEG-03", name: "Tomato", category: "Fresh", unit: "kg", sku: "SKU-VEG-03", barcode: "6001003", queensPrice: 55.00, active: true },
    { id: "VEG-04", name: "Carrot", category: "Fresh", unit: "kg", sku: "SKU-VEG-04", barcode: "6001004", queensPrice: 42.00, active: true },
    { id: "VEG-05", name: "Cabbage", category: "Fresh", unit: "kg", sku: "SKU-VEG-05", barcode: "6001005", queensPrice: 35.00, active: true },

    // Ultra-Sensitive & Staples (5 Items)
    { id: "EDO-01", name: "Sunflower Oil 5L", category: "Ultra-Sensitive", unit: "pcs", sku: "SKU-EDO-01", barcode: "6002001", queensPrice: 890.00, active: true },
    { id: "EDO-02", name: "Palm Cooking Oil 3L", category: "Ultra-Sensitive", unit: "pcs", sku: "SKU-EDO-02", barcode: "6002002", queensPrice: 520.00, active: true },
    { id: "SUG-01", name: "White Sugar 1kg", category: "Ultra-Sensitive", unit: "kg", sku: "SKU-SUG-01", barcode: "6002003", queensPrice: 110.00, active: true },
    { id: "FLR-01", name: "Wheat Flour 5kg", category: "Sensitive", unit: "pcs", sku: "SKU-FLR-01", barcode: "6002004", queensPrice: 380.00, active: true },
    { id: "RIC-01", name: "Basmati Rice 5kg", category: "Sensitive", unit: "pcs", sku: "SKU-RIC-01", barcode: "6002005", queensPrice: 720.00, active: true },

    // Packaged FMCG & Dairy (5 Items)
    { id: "PAS-01", name: "Spaghetti 500g", category: "Non-Sensitive", unit: "pcs", sku: "SKU-PAS-01", barcode: "6003001", queensPrice: 75.00, active: true },
    { id: "PAS-02", name: "Macaroni 500g", category: "Non-Sensitive", unit: "pcs", sku: "SKU-PAS-02", barcode: "6003002", queensPrice: 72.00, active: true },
    { id: "MLK-01", name: "Pasteurized Milk 500ml", category: "Sensitive", unit: "pcs", sku: "SKU-MLK-01", barcode: "6003003", queensPrice: 45.00, active: true },
    { id: "EGG-01", name: "Table Eggs 30-Pack", category: "Sensitive", unit: "crate", sku: "SKU-EGG-01", barcode: "6003004", queensPrice: 420.00, active: true },
    { id: "WAT-01", name: "Cheers 10L Bottled Water", category: "Non-Sensitive", unit: "pcs", sku: "SKU-WAT-01", barcode: "6003005", queensPrice: 135.00, active: true },

    // Baking, Tea & Personal Essentials (5 Items)
    { id: "TEA-01", name: "Black Tea 100 Tea Bags", category: "Non-Sensitive", unit: "box", sku: "SKU-TEA-01", barcode: "6004001", queensPrice: 165.00, active: true },
    { id: "COF-01", name: "Roasted Coffee Beans 500g", category: "Sensitive", unit: "pack", sku: "SKU-COF-01", barcode: "6004002", queensPrice: 340.00, active: true },
    { id: "SLT-01", name: "Iodized Table Salt 1kg", category: "Dry", unit: "kg", sku: "SKU-SLT-01", barcode: "6004003", queensPrice: 28.00, active: true },
    { id: "SOP-01", name: "Laundry Bar Soap 250g", category: "Non-Sensitive", unit: "pcs", sku: "SKU-SOP-01", barcode: "6004004", queensPrice: 55.00, active: true },
    { id: "DET-01", name: "Washing Powder Detergent 1kg", category: "Non-Sensitive", unit: "pcs", sku: "SKU-DET-01", barcode: "6004005", queensPrice: 240.00, active: true },
];